repos:
- hooks:
  - id: black
  repo: https://github.com/psf/black
  rev: 21.12b0
- hooks:
  - id: flake8
  repo: https://gitlab.com/pycqa/flake8
  rev: 3.9.2
- hooks:
  - id: isort
  repo: https://github.com/PyCQA/isort
  rev: 5.10.1
- hooks:
  - id: commitizen
    stages:
    - commit-msg
  repo: https://github.com/commitizen-tools/commitizen
  rev: v2.20.3
