git:
  depth: false

sudo: false

language: python

matrix:
  fast_finish: true

python:
  - "3.7"
  - "3.8"
  - "3.9"
  - "3.10"
  - "nightly"

before_install:
  - pip install poetry

install:
  - poetry install -E aio

script:
  - poetry run flake8 src/keycloak tests/keycloak
  - poetry run pytest --addopts "$TEST_OPTS"

after_success:
  - codecov
